// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using slender_server.Infra.Database;

#nullable disable

namespace slender_server.Infra.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("slender")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("slender_server.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_activity_logs");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_activity_logs_actor_id");

                    b.HasIndex("CreatedAtUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_ActivityLogs_CreatedAt");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_activity_logs_workspace_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_ActivityLogs_Entity");

                    b.HasIndex("WorkspaceId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ActivityLogs_Workspace_CreatedAt");

                    b.ToTable("activity_logs", "slender", t =>
                        {
                            t.HasCheckConstraint("CK_ActivityLog_ActionNotEmpty", "LENGTH(TRIM(\"action\")) > 0");

                            t.HasCheckConstraint("CK_ActivityLog_EntityIdNotEmpty", "LENGTH(TRIM(\"entity_id\")) > 0");

                            t.HasCheckConstraint("CK_ActivityLog_EntityTypeNotEmpty", "LENGTH(TRIM(\"entity_type\")) > 0");
                        });
                });

            modelBuilder.Entity("slender_server.Domain.Entities.CalendarEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_day");

                    b.Property<string>("ScheduleType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schedule_type");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("TaskId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_calendar_events");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("IX_CalendarEvents_Task")
                        .HasFilter("\"task_id\" IS NOT NULL");

                    b.HasIndex("CreatedById", "StartsAtUtc")
                        .HasDatabaseName("IX_CalendarEvents_Creator_StartsAt");

                    b.HasIndex("WorkspaceId", "StartsAtUtc")
                        .HasDatabaseName("IX_CalendarEvents_Workspace_StartsAt");

                    b.HasIndex("WorkspaceId", "StartsAtUtc", "EndsAtUtc")
                        .HasDatabaseName("IX_CalendarEvents_Workspace_DateRange");

                    b.ToTable("calendar_events", "slender", t =>
                        {
                            t.HasCheckConstraint("CK_CalendarEvent_AllDayMidnight", "(\"is_all_day\" = false) OR \n          (\"is_all_day\" = true AND \n           EXTRACT(HOUR FROM \"starts_at_utc\") = 0 AND \n           EXTRACT(MINUTE FROM \"starts_at_utc\") = 0 AND \n           EXTRACT(SECOND FROM \"starts_at_utc\") = 0 AND\n           EXTRACT(HOUR FROM \"ends_at_utc\") = 0 AND \n           EXTRACT(MINUTE FROM \"ends_at_utc\") = 0 AND \n           EXTRACT(SECOND FROM \"ends_at_utc\") = 0)");

                            t.HasCheckConstraint("CK_CalendarEvent_EndsAfterStarts", "\"ends_at_utc\" > \"starts_at_utc\"");

                            t.HasCheckConstraint("CK_CalendarEvent_TitleNotEmpty", "LENGTH(TRIM(\"title\")) > 0");

                            t.HasCheckConstraint("CK_CalendarEvent_ValidScheduleType", "\"schedule_type\" IS NULL OR \n          \"schedule_type\" IN ('Meeting', 'Task', 'Review', 'Event', 'Reminder')");
                        });
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Channel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("ParticipantHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("participant_hash")
                        .IsFixedLength();

                    b.Property<string>("ProjectId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_channels_created_by_id");

                    b.HasIndex("ParticipantHash")
                        .HasDatabaseName("ix_channels_participant_hash")
                        .HasFilter("\"type\" = 'DirectMessage'");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_channels_project_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_channels_workspace_id")
                        .HasFilter("\"type\" = 'DirectMessage'");

                    b.HasIndex("WorkspaceId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_channels_workspace_id_created_at_utc");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_workspace_id_name")
                        .HasFilter("\"name\" IS NOT NULL");

                    b.HasIndex("WorkspaceId", "ParticipantHash")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_workspace_id_participant_hash")
                        .HasFilter("\"participant_hash\" IS NOT NULL");

                    b.HasIndex("WorkspaceId", "ProjectId")
                        .HasDatabaseName("ix_channels_workspace_id_project_id")
                        .HasFilter("\"project_id\" IS NOT NULL");

                    b.ToTable("channels", "slender", t =>
                        {
                            t.HasCheckConstraint("CK_Channel_NameRules", "(\"type\" = 'DirectMessage' AND \"name\" IS NULL) OR \n(\"type\" IN ('Public', 'Private') AND \"name\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Channel_ParticipantHashOnlyForDMs", "(\"type\" = 'DirectMessage' AND \"participant_hash\" IS NOT NULL) OR \n(\"type\" IN ('Public', 'Private') AND \"participant_hash\" IS NULL)");

                            t.HasCheckConstraint("CK_Channel_ProjectScope", "(\"type\" = 'DirectMessage' AND \"project_id\" IS NULL) OR \n(\"type\" IN ('Public', 'Private'))");
                        });
                });

            modelBuilder.Entity("slender_server.Domain.Entities.ChannelMember", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("channel_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime?>("LastReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_read_at_utc");

                    b.HasKey("ChannelId", "UserId")
                        .HasName("pk_channel_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ChannelMembers_UserId_Unread")
                        .HasFilter("\"last_read_at_utc\" IS NULL");

                    b.ToTable("channel_members", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Label", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_labels");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_labels_workspace_id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_labels_workspace_id_name");

                    b.ToTable("labels", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("ReplyToId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reply_to_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ReplyToId")
                        .HasDatabaseName("IX_Messages_ReplyTo")
                        .HasFilter("\"reply_to_id\" IS NOT NULL AND \"deleted_at_utc\" IS NULL");

                    b.HasIndex("AuthorId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Messages_Author_Created")
                        .HasFilter("\"deleted_at_utc\" IS NULL");

                    b.HasIndex("ChannelId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Messages_Channel_Created")
                        .HasFilter("\"deleted_at_utc\" IS NULL");

                    b.ToTable("messages", "slender", t =>
                        {
                            t.HasCheckConstraint("CK_Message_BodyNotEmpty", "LENGTH(TRIM(\"body\")) > 0");

                            t.HasCheckConstraint("CK_Message_NoSelfReply", "\"id\" != \"reply_to_id\"");

                            t.HasCheckConstraint("CK_Message_UpdatedAfterCreated", "\"updated_at_utc\" >= \"created_at_utc\"");
                        });
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("EntityName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("entity_name");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recipient_id");

                    b.Property<string>("TaskId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_notifications_actor_id");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("IX_Notifications_Unread")
                        .HasFilter("\"read_at_utc\" IS NULL");

                    b.HasIndex("RecipientId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Notifications_Recipient_Created");

                    b.ToTable("notifications", "slender", t =>
                        {
                            t.HasCheckConstraint("CK_Notification_SingleTarget", "(CASE WHEN \"workspace_id\" IS NOT NULL THEN 1 ELSE 0 END +\n                   CASE WHEN \"project_id\" IS NOT NULL THEN 1 ELSE 0 END +\n                   CASE WHEN \"task_id\" IS NOT NULL THEN 1 ELSE 0 END) <= 1");
                        });
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("owner_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_projects_owner_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_projects_workspace_id");

                    b.HasIndex("WorkspaceId", "Status")
                        .HasDatabaseName("ix_projects_workspace_id_status");

                    b.ToTable("projects", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.Property<string>("AddedByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("added_by_user_id");

                    b.Property<DateTime>("JoinedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_project_members");

                    b.HasIndex("AddedByUserId")
                        .HasDatabaseName("ix_project_members_added_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_members_user_id");

                    b.ToTable("project_members", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Task", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("ParentTaskId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parent_task_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<double>("SortOrder")
                        .HasColumnType("double precision")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_tasks_created_by_id");

                    b.HasIndex("ParentTaskId")
                        .HasDatabaseName("ix_tasks_parent_task_id")
                        .HasFilter("\"parent_task_id\" IS NOT NULL");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("ix_tasks_scheduled_at")
                        .HasFilter("\"scheduled_at\" IS NOT NULL");

                    b.HasIndex("WorkspaceId", "Status")
                        .HasDatabaseName("ix_tasks_workspace_id_status");

                    b.HasIndex("ProjectId", "Status", "SortOrder")
                        .HasDatabaseName("ix_tasks_project_id_status_sort_order");

                    b.ToTable("tasks", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.TaskAssignee", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("AssignedById")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assigned_by_id");

                    b.HasKey("TaskId", "UserId")
                        .HasName("pk_task_assignees");

                    b.HasIndex("AssignedById")
                        .HasDatabaseName("ix_task_assignees_assigned_by_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_assignees_task_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_task_assignees_user_id");

                    b.ToTable("task_assignees", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.TaskAttachment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_url");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_id");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id")
                        .HasName("pk_task_attachments");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_attachments_task_id");

                    b.HasIndex("UploadedById")
                        .HasDatabaseName("ix_task_attachments_uploaded_by_id");

                    b.ToTable("task_attachments", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.TaskComment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("ParentCommentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parent_comment_id");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_task_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_task_comments_author_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_task_comments_parent_comment_id")
                        .HasFilter("\"parent_comment_id\" IS NOT NULL");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_comments_task_id");

                    b.ToTable("task_comments", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.TaskCommentAttachment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_url");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id")
                        .HasName("pk_task_comment_attachments");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_task_comment_attachments_comment_id");

                    b.HasIndex("UploadedById")
                        .HasDatabaseName("ix_task_comment_attachments_uploaded_by_id");

                    b.ToTable("task_comment_attachments", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.TaskLabel", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_id");

                    b.Property<string>("LabelId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_id");

                    b.HasKey("TaskId", "LabelId")
                        .HasName("pk_task_labels");

                    b.HasIndex("LabelId")
                        .HasDatabaseName("ix_task_labels_label_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_labels_task_id");

                    b.ToTable("task_labels", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("avatar_color");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identity_id");

                    b.Property<DateTime?>("LastActiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.ToTable("users", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Workspace", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("owner_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_workspaces_owner_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_workspaces_slug");

                    b.ToTable("workspaces", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.WorkspaceInvite", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("InvitedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("token");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_invites");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_workspace_invites_invited_by_user_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_invites_token");

                    b.HasIndex("WorkspaceId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_invites_workspace_id_email")
                        .HasFilter("\"accepted_at_utc\" IS NULL");

                    b.ToTable("workspace_invites", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workspace_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.Property<string>("InvitedByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invited_by_user_id");

                    b.Property<DateTime>("JoinedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("WorkspaceId", "UserId")
                        .HasName("pk_workspace_members");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_workspace_members_invited_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workspace_members_user_id");

                    b.ToTable("workspace_members", "slender");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_logs_users_actor_id");

                    b.HasOne("slender_server.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_logs_workspaces_workspace_id");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.CalendarEvent", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_events_users_created_by_id");

                    b.HasOne("slender_server.Domain.Entities.Task", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_calendar_events_tasks_task_id");

                    b.HasOne("slender_server.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_events_workspaces_workspace_id");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Channel", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_channels_users_created_by_id");

                    b.HasOne("slender_server.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_channels_projects_project_id");

                    b.HasOne("slender_server.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channels_workspaces_workspace_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.ChannelMember", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.Channel", "Channel")
                        .WithMany("Members")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_members_channels_channel_id");

                    b.HasOne("slender_server.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_channel_members_users_user_id");

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Label", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_labels_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Message", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_author_id");

                    b.HasOne("slender_server.Domain.Entities.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_channels_channel_id");

                    b.HasOne("slender_server.Domain.Entities.Message", "ReplyToMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_messages_messages_reply_to_id");

                    b.Navigation("Author");

                    b.Navigation("Channel");

                    b.Navigation("ReplyToMessage");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Notification", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_users_actor_id");

                    b.HasOne("slender_server.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_recipient_id");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Project", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_users_owner_id");

                    b.HasOne("slender_server.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Projects")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_workspaces_workspace_id");

                    b.Navigation("Owner");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_members_users_added_by_user_id");

                    b.HasOne("slender_server.Domain.Entities.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.HasOne("slender_server.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_users_user_id");

                    b.Navigation("AddedByUser");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Task", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tasks_users_created_by_id");

                    b.HasOne("slender_server.Domain.Entities.Task", "ParentTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tasks_tasks_parent_task_id");

                    b.HasOne("slender_server.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_projects_project_id");

                    b.HasOne("slender_server.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_workspaces_workspace_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("ParentTask");

                    b.Navigation("Project");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.TaskAssignee", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_task_assignees_users_assigned_by_id");

                    b.HasOne("slender_server.Domain.Entities.Task", "Task")
                        .WithMany("Assignees")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_assignees_tasks_task_id");

                    b.HasOne("slender_server.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_assignees_users_user_id");

                    b.Navigation("AssignedBy");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.TaskAttachment", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.Task", "Task")
                        .WithMany("Attachments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_attachments_tasks_task_id");

                    b.HasOne("slender_server.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_attachments_users_uploaded_by_id");

                    b.Navigation("Task");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.TaskComment", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_task_comments_users_author_id");

                    b.HasOne("slender_server.Domain.Entities.TaskComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_task_comments_task_comments_parent_comment_id");

                    b.HasOne("slender_server.Domain.Entities.Task", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_comments_tasks_task_id");

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.TaskCommentAttachment", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.TaskComment", "TaskComment")
                        .WithMany("Attachments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_comment_attachments_task_comments_comment_id");

                    b.HasOne("slender_server.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_comment_attachments_users_uploaded_by_id");

                    b.Navigation("TaskComment");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.TaskLabel", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.Label", "Label")
                        .WithMany("TaskLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_labels_labels_label_id");

                    b.HasOne("slender_server.Domain.Entities.Task", "Task")
                        .WithMany("Labels")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_labels_tasks_task_id");

                    b.Navigation("Label");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.WorkspaceInvite", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_invites_users_invited_by_user_id");

                    b.HasOne("slender_server.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Invites")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_invites_workspaces_workspace_id");

                    b.Navigation("InvitedByUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("slender_server.Domain.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workspace_members_users_invited_by_user_id");

                    b.HasOne("slender_server.Domain.Entities.User", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_users_user_id");

                    b.HasOne("slender_server.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspaces_workspace_id");

                    b.Navigation("InvitedByUser");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Channel", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Label", b =>
                {
                    b.Navigation("TaskLabels");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Message", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Project", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Task", b =>
                {
                    b.Navigation("Assignees");

                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("Labels");

                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.TaskComment", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.User", b =>
                {
                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("slender_server.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Members");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
